package com.enums;

public enum OrderStatusOutput {

    CREATED("CREATED"),
    PENDING_PAYMENT("PENDING_PAYMENT"),
    REDIRECTED("REDIRECTED"),ACCOUNT_VERIFIED("ACCOUNT_VERIFIED"),PENDING_MERCHANT("PENDING_MERCHANT"),PENDING_APPROVAL("PENDING_APPROVAL"),
    PENDING_FRAUD_APPROVAL("PENDING_FRAUD_APPROVAL"),PENDING_CONNECT_OR_3RD_PARTY("PENDING_CONNECT_OR_3RD_PARTY"),AUTHORIZATION_REQUESTED("AUTHORIZATION_REQUESTED"),CAPTURE_REQUESTED("CAPTURE_REQUESTED"),PAYOUT_REQUESTED("PAYOUT_REQUESTED"),

    REFUND_REQUESTED("REFUND_REQUESTED"),COMPLETED("COMPLETED"),CAPTURED("CAPTURED"),PAID("PAID"),ACCOUNT_CREDITED("ACCOUNT_CREDITED"),REVERSED("REVERSED"),CHARGEBACKED("CHARGEBACKED"),REFUNDED("REFUNDED"),UNSUCCESSFUL("UNSUCCESSFUL"),
    CANCELLED("CANCELLED"),REJECTED("REJECTED"),REJECTED_CAPTURE("REJECTED_CAPTURE"),REJECTED_CREDIT("REJECTED_CREDIT")

    ;

    private String url;

    OrderStatusOutput(String url) {
        this.url = url;
    }

    public String url() {
        return url;
    }

}
